sudo: required
dist: xenial

language:
- cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

before_install:
- sudo apt-get update -q
- sudo apt-get install gcc g++ python -y

script:
- python waf configure
- python waf debug
- python waf

after_success:
- ./build/debug/bin/unit_test-debug