sudo: required
dist: xenial

language:
- cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

before_install:
- ORIG_DIR=$(pwd)
- sudo apt-get update -q
- sudo apt-get install gcc g++ python libgtest-dev cmake -y
- cd /usr/src/gtest
- sudo cmake .
- sudo make
- sudo mv libg* /usr/lib/
- cd $ORIG_DIR

script:
- python waf configure
- python waf debug
- python waf

after_success:
- ./build/debug/bin/unit_test-debug