image:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

environment:
  global:
    PROJECT_NAME: rustfp

clone_script:
  - git clone -q --recursive --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - git checkout -qf %APPVEYOR_REPO_COMMIT%

build_script:
  - mkdir build
  - cd build
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" set CMAKE_GENERATOR_VS=Visual Studio 14 2015
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set CMAKE_GENERATOR_VS=Visual Studio 15 2017
  - if "%PLATFORM%"=="x86" set CMAKE_GENERATOR_NAME=%CMAKE_GENERATOR_VS%
  - if "%PLATFORM%"=="x64" set CMAKE_GENERATOR_NAME=%CMAKE_GENERATOR_VS% Win64
  - cmake .. -G "%CMAKE_GENERATOR_NAME%"
  - msbuild /m:4 /p:Configuration=%CONFIGURATION% rustfp.sln
