image:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Win32 
  - x64

configuration:
  - Debug
  - Release

branches:
  only:
    - master

build:
  parallel: true

matrix:
  fast_finish: true

environment:
  global:
    PROJECT_NAME: rustfp

build_script:
  - git rev-parse HEAD
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" set CMAKE_GENERATOR_VS=Visual Studio 14 2015
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" set CMAKE_GENERATOR_VS=Visual Studio 15 2017
  - if "%PLATFORM%"=="Win32" set CMAKE_GENERATOR_NAME=%CMAKE_GENERATOR_VS%
  - if "%PLATFORM%"=="x64" set CMAKE_GENERATOR_NAME=%CMAKE_GENERATOR_VS% Win64
  - cmake .. -G "%CMAKE_GENERATOR_NAME%" -DRUSTFP_INCLUDE_UNIT_TESTS=ON -DCMAKE_INSTALL_PREFIX:PATH=install
  - cmake --build . --config %CONFIGURATION% --target install
  - ctest -R rustfp_unit_test -V
